# Generated by Django 2.2.7 on 2022-06-18 11:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='Bbosa', max_length=10)),
                ('phone', models.CharField(db_index=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format         +256706626855. Up to 10 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 18, 11, 14, 57, 438449))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 6, 18, 11, 14, 57, 438449))),
                ('country', models.CharField(choices=[('UGA', 'Uganda'), ('KEN', 'Kenya'), ('NIG', 'Nigeria')], default='UGA', max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'unique_together': {('phone', 'email')},
            },
        ),
    ]
